### PR TITLE
FIX Add CMS configurable title for iframe to tell screenreaders it contains frame content

### PR DESCRIPTION
**Pull request by robbieaverill**
Issue: https://github.com/silverstripe/silverstripe-iframe/issues/43

### CODE REVIEW

**Comment by robbieaverill** [comment]
That's always a chance I suppose. Waiting on @sachajudd's review before merge by the way.

**Comment by sachajudd** [comment]
Hey @robbieaverill couple of quick suggestions:

Could the label for the field be: "Description of contents (title)" and the description: "Used by screen readers".

Would I be able to see a screenshot of the whole area as well?

**Comment by robbieaverill** [comment]
It's not just used by screenreaders though right?

**Comment by sachajudd** [comment]
Can you suggest alternative wording?

**Comment by robbieaverill** [comment]
We discussed off GitHub and looked at some references, decided that @sachajudd's suggestion is suitable :)

**Comment by robbieaverill** [comment]
Updated. We're down a couple of percent on code coverage, but I'm not convinced it's worth writing tests for the CMS field that isn't covered.

**Pull request merged**
